### ISSUE TITLE
The dependency on version is incompatible with paper_trails version class

### ISSUE THREAD

**Issue by mhenrixon** [johnbintz/guard-rails#25]
All of a sudden (after upgrading guard-rails) to latest version we get the following errors

``` sh
Started GET "/" for 127.0.0.1 at 2013-02-25 11:25:13 +0100
Processing by PagesController#show as HTML
  Site Load (0.3ms)  SELECT "sites".* FROM "sites" WHERE "sites"."subdomain" = 'dev' LIMIT 1
  Page Load (0.3ms)  SELECT "pages".* FROM "pages" WHERE "pages"."site_id" = 1 AND "pages"."url" = '' LIMIT 1
  Version Load (0.4ms)  SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = 1 AND "versions"."item_type" = 'Page' AND "versions"."published_at" = '2013-02-21 17:30:23.241998' ORDER BY created_at ASC, id ASC LIMIT 1
Completed 500 Internal Server Error in 6ms

NoMethodError (protected method `[]' called for "":Version):
  app/models/concerns/versionable.rb:69:in `published_version'
  app/controllers/pages_controller.rb:9:in `show'
  app/controllers/application_controller.rb:172:in `set_logger_site_id'
  app/controllers/application_controller.rb:178:in `set_logger_username'
```

**Comment by johnbintz** [comment]
This project has been taken over by @ranmocy: http://github.com/ranmocy/guard-rails

**Comment by mhenrixon** [comment]
Ya I already posted there the link to the issue : https://github.com/ranmocy/guard-rails/issues/2

**Comment by johnbintz** [comment]
Cool. Good luck!
